"""Every HTML element, one class each.

**Generated by ``scripts/generate_elements.py`` from ``winged._tagtable``. Do not edit.**

Adding an element is a row in that table and a re-run of the generator. 0.1.0 kept 49
hand-written modules whose only content was three class attributes each; this replaces
them, and it is why ``docs/tag-catalog.md`` can be generated rather than maintained.

Elements that require an argument -- :class:`Img` needs ``alt``, :class:`Iframe` needs
``title`` -- are defined in :mod:`winged._special` and re-exported here. That requirement
is an accessibility guarantee enforced by the signature, as it is in WingedSwift.
"""

from __future__ import annotations

from ._special import Iframe, Img
from .core.element import AttrValue, Element
from .core.node import Child

__all__ = [
    "A",
    "Abbr",
    "Address",
    "Article",
    "Aside",
    "Audio",
    "Base",
    "Blockquote",
    "Body",
    "Br",
    "Button",
    "Canvas",
    "Caption",
    "Cite",
    "Code",
    "Col",
    "Colgroup",
    "Datalist",
    "Dd",
    "Del",
    "Details",
    "Dialog",
    "Div",
    "Dl",
    "Dt",
    "Em",
    "Embed",
    "Fieldset",
    "Figcaption",
    "Figure",
    "Footer",
    "Form",
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "Head",
    "Header",
    "Hr",
    "I",
    "Iframe",
    "Img",
    "Input",
    "Ins",
    "Kbd",
    "Label",
    "Legend",
    "Li",
    "Link",
    "Main",
    "Mark",
    "Meta",
    "Meter",
    "Nav",
    "Noscript",
    "Ol",
    "Optgroup",
    "Option",
    "Output",
    "P",
    "Picture",
    "Pre",
    "Progress",
    "Q",
    "Samp",
    "Script",
    "Section",
    "Select",
    "Small",
    "Source",
    "Span",
    "Strong",
    "Style",
    "Sub",
    "Summary",
    "Sup",
    "Table",
    "Tbody",
    "Td",
    "Textarea",
    "Tfoot",
    "Th",
    "Thead",
    "Time",
    "Title",
    "Tr",
    "Track",
    "Ul",
    "Var",
    "Video",
    "Wbr",
]


class A(Element):
    """The ``<a>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("a", *children, **attrs)


class Abbr(Element):
    """The ``<abbr>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("abbr", *children, **attrs)


class Address(Element):
    """The ``<address>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("address", *children, **attrs)


class Article(Element):
    """The ``<article>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("article", *children, **attrs)


class Aside(Element):
    """The ``<aside>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("aside", *children, **attrs)


class Base(Element):
    """The ``<base>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("base", **attrs)


class Blockquote(Element):
    """The ``<blockquote>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("blockquote", *children, **attrs)


class Body(Element):
    """The ``<body>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("body", *children, **attrs)


class Br(Element):
    """The ``<br>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("br", **attrs)


class Button(Element):
    """The ``<button>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("button", *children, **attrs)


class Canvas(Element):
    """The ``<canvas>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("canvas", *children, **attrs)


class Cite(Element):
    """The ``<cite>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("cite", *children, **attrs)


class Dd(Element):
    """The ``<dd>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("dd", *children, **attrs)


class Del(Element):
    """The ``<del>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("del", *children, **attrs)


class Details(Element):
    """The ``<details>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("details", *children, **attrs)


class Dialog(Element):
    """The ``<dialog>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("dialog", *children, **attrs)


class Div(Element):
    """The ``<div>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("div", *children, **attrs)


class Dl(Element):
    """The ``<dl>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("dl", *children, **attrs)


class Dt(Element):
    """The ``<dt>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("dt", *children, **attrs)


class Em(Element):
    """The ``<em>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("em", *children, **attrs)


class Figcaption(Element):
    """The ``<figcaption>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("figcaption", *children, **attrs)


class Figure(Element):
    """The ``<figure>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("figure", *children, **attrs)


class Footer(Element):
    """The ``<footer>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("footer", *children, **attrs)


class H1(Element):
    """The ``<h1>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("h1", *children, **attrs)


class H2(Element):
    """The ``<h2>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("h2", *children, **attrs)


class H3(Element):
    """The ``<h3>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("h3", *children, **attrs)


class H4(Element):
    """The ``<h4>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("h4", *children, **attrs)


class H5(Element):
    """The ``<h5>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("h5", *children, **attrs)


class H6(Element):
    """The ``<h6>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("h6", *children, **attrs)


class Head(Element):
    """The ``<head>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("head", *children, **attrs)


class Header(Element):
    """The ``<header>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("header", *children, **attrs)


class Hr(Element):
    """The ``<hr>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("hr", **attrs)


class I(Element):
    """The ``<i>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("i", *children, **attrs)


class Ins(Element):
    """The ``<ins>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("ins", *children, **attrs)


class Kbd(Element):
    """The ``<kbd>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("kbd", *children, **attrs)


class Li(Element):
    """The ``<li>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("li", *children, **attrs)


class Link(Element):
    """The ``<link>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("link", **attrs)


class Main(Element):
    """The ``<main>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("main", *children, **attrs)


class Mark(Element):
    """The ``<mark>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("mark", *children, **attrs)


class Meta(Element):
    """The ``<meta>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("meta", **attrs)


class Nav(Element):
    """The ``<nav>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("nav", *children, **attrs)


class Noscript(Element):
    """The ``<noscript>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("noscript", *children, **attrs)


class Ol(Element):
    """The ``<ol>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("ol", *children, **attrs)


class P(Element):
    """The ``<p>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("p", *children, **attrs)


class Picture(Element):
    """The ``<picture>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("picture", *children, **attrs)


class Q(Element):
    """The ``<q>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("q", *children, **attrs)


class Samp(Element):
    """The ``<samp>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("samp", *children, **attrs)


class Script(Element):
    """The ``<script>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("script", *children, **attrs)


class Section(Element):
    """The ``<section>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("section", *children, **attrs)


class Small(Element):
    """The ``<small>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("small", *children, **attrs)


class Span(Element):
    """The ``<span>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("span", *children, **attrs)


class Strong(Element):
    """The ``<strong>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("strong", *children, **attrs)


class Style(Element):
    """The ``<style>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("style", *children, **attrs)


class Sub(Element):
    """The ``<sub>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("sub", *children, **attrs)


class Summary(Element):
    """The ``<summary>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("summary", *children, **attrs)


class Sup(Element):
    """The ``<sup>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("sup", *children, **attrs)


class Table(Element):
    """The ``<table>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("table", *children, **attrs)


class Td(Element):
    """The ``<td>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("td", *children, **attrs)


class Th(Element):
    """The ``<th>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("th", *children, **attrs)


class Time(Element):
    """The ``<time>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("time", *children, **attrs)


class Title(Element):
    """The ``<title>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("title", *children, **attrs)


class Tr(Element):
    """The ``<tr>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("tr", *children, **attrs)


class Ul(Element):
    """The ``<ul>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("ul", *children, **attrs)


class Var(Element):
    """The ``<var>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("var", *children, **attrs)


class Wbr(Element):
    """The ``<wbr>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("wbr", **attrs)


class Datalist(Element):
    """The ``<datalist>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("datalist", *children, **attrs)


class Fieldset(Element):
    """The ``<fieldset>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("fieldset", *children, **attrs)


class Form(Element):
    """The ``<form>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("form", *children, **attrs)


class Input(Element):
    """The ``<input>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("input", **attrs)


class Label(Element):
    """The ``<label>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("label", *children, **attrs)


class Legend(Element):
    """The ``<legend>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("legend", *children, **attrs)


class Meter(Element):
    """The ``<meter>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("meter", *children, **attrs)


class Optgroup(Element):
    """The ``<optgroup>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("optgroup", *children, **attrs)


class Option(Element):
    """The ``<option>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("option", *children, **attrs)


class Output(Element):
    """The ``<output>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("output", *children, **attrs)


class Progress(Element):
    """The ``<progress>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("progress", *children, **attrs)


class Select(Element):
    """The ``<select>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("select", *children, **attrs)


class Textarea(Element):
    """The ``<textarea>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("textarea", *children, **attrs)


class Caption(Element):
    """The ``<caption>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("caption", *children, **attrs)


class Col(Element):
    """The ``<col>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("col", **attrs)


class Colgroup(Element):
    """The ``<colgroup>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("colgroup", *children, **attrs)


class Tbody(Element):
    """The ``<tbody>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("tbody", *children, **attrs)


class Tfoot(Element):
    """The ``<tfoot>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("tfoot", *children, **attrs)


class Thead(Element):
    """The ``<thead>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("thead", *children, **attrs)


class Audio(Element):
    """The ``<audio>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("audio", *children, **attrs)


class Source(Element):
    """The ``<source>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("source", **attrs)


class Track(Element):
    """The ``<track>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("track", **attrs)


class Video(Element):
    """The ``<video>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("video", *children, **attrs)


class Code(Element):
    """The ``<code>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("code", *children, **attrs)


class Embed(Element):
    """The ``<embed>`` element. A void element: it takes attributes only."""

    def __init__(self, **attrs: AttrValue) -> None:
        super().__init__("embed", **attrs)


class Pre(Element):
    """The ``<pre>`` element. A container element."""

    def __init__(self, *children: Child, **attrs: AttrValue) -> None:
        super().__init__("pre", *children, **attrs)
