#!/usr/bin/env python3
"""Generate ``src/winged/elements.py`` from the table in ``winged._tagtable``.

Ports the idea behind ``Winged-Swift/Scripts/generate-builder-inits.py``: repetitive API
surface is generated, and the output is committed and reviewed like handwritten code.
``--check`` fails when the file on disk is stale, and runs in CI and ``verify.sh``.

The point is that each element gets a *real* ``def`` with a precise signature, so
``mypy --strict`` sees ``Div(*children: Child, **attrs: AttrValue) -> None`` rather than a
dynamically built class it knows nothing about.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from winged._tagtable import TAGS  # noqa: E402
from winged.core.tags import VOID_ELEMENTS  # noqa: E402

TARGET = ROOT / "src" / "winged" / "elements.py"

HEADER = '''"""Every HTML element, one class each.

**Generated by ``scripts/generate_elements.py`` from ``winged._tagtable``. Do not edit.**

Adding an element is a row in that table and a re-run of the generator. 0.1.0 kept 49
hand-written modules whose only content was three class attributes each; this replaces
them, and it is why ``docs/tag-catalog.md`` can be generated rather than maintained.

Elements that require an argument -- :class:`Img` needs ``alt``, :class:`Iframe` needs
``title`` -- are defined in :mod:`winged._special` and re-exported here. That requirement
is an accessibility guarantee enforced by the signature, as it is in WingedSwift.
"""

from __future__ import annotations

from ._special import Iframe, Img
from .core.element import AttrValue, Element
from .core.node import Child

'''


def render_class(name: str, tag: str, void: bool) -> str:
    kind = "A void element: it takes attributes only." if void else "A container element."
    body = f'    """The ``<{tag}>`` element. {kind}"""\n\n'
    if void:
        body += (
            "    def __init__(self, **attrs: AttrValue) -> None:\n"
            f'        super().__init__("{tag}", **attrs)\n'
        )
    else:
        body += (
            "    def __init__(self, *children: Child, **attrs: AttrValue) -> None:\n"
            f'        super().__init__("{tag}", *children, **attrs)\n'
        )
    return f"class {name}(Element):\n{body}"


def generate() -> str:
    names = sorted([t[0] for t in TAGS] + ["Iframe", "Img"])
    # Two blank lines before the first class and between classes, none trailing: the
    # output has to satisfy `ruff format --check`, or the freshness check in CI and the
    # format check would disagree forever.
    all_line = "__all__ = [\n" + "".join(f'    "{n}",\n' for n in names) + "]\n\n\n"
    blocks = [render_class(name, tag, tag in VOID_ELEMENTS) for name, tag, _ in TAGS]
    return HEADER + all_line + "\n\n".join(blocks)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    expected = generate()
    if args.check:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != expected:
            print(f"{TARGET.relative_to(ROOT)} is stale — run scripts/generate_elements.py")
            return 1
        print(f"{TARGET.relative_to(ROOT)} is current")
        return 0

    TARGET.write_text(expected)
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(TAGS) + 2} elements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
