#!/usr/bin/env python3
"""Generate ``docs/tag-catalog.md`` from the element table.

Ports ``Winged-Swift/Scripts/generate-tag-catalog.sh``.

The catalogue is the file most likely to drift from the code, which is exactly why it is
generated rather than maintained. ``--check`` runs in CI and in ``scripts/verify.sh``, so
a tag added without regenerating fails the build.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from winged._tagtable import TAGS  # noqa: E402
from winged.core.tags import VOID_ELEMENTS, WHITESPACE_SENSITIVE  # noqa: E402

TARGET = ROOT / "docs" / "tag-catalog.md"

PREAMBLE = """# Tag catalogue

**Generated by `scripts/generate_tag_catalog.py`. Do not edit.**

Every element Winged-Python ships. A *void* element has no closing tag and takes no
children; a *whitespace-sensitive* element renders compactly even in pretty mode, because
indentation inside it changes what the browser displays.

Container elements take children positionally and attributes by keyword:

```python
Div(H1("Title"), P("Body"), cls="card")
```

Attribute names that collide with a Python keyword or builtin take a trailing underscore
(`cls`, `for_`, `type_`, `id_`); the rendered attribute is always the HTML spelling.

"""


def rows() -> list[tuple[str, str, str, str]]:
    out = []
    for name, tag, _group in sorted(TAGS):
        kinds = []
        if tag in VOID_ELEMENTS:
            kinds.append("void")
        if tag in WHITESPACE_SENSITIVE:
            kinds.append("whitespace-sensitive")
        signature = f"{name}(**attrs)" if tag in VOID_ELEMENTS else f"{name}(*children, **attrs)"
        out.append((f"`<{tag}>`", f"`{name}`", f"`{signature}`", ", ".join(kinds) or "container"))
    # The two that require an argument live in winged._special.
    out.append(("`<img>`", "`Img`", "`Img(src, alt, **attrs)`", "void, `alt` required"))
    out.append(
        ("`<iframe>`", "`Iframe`", "`Iframe(src, title, **attrs)`", "container, `title` required")
    )
    return sorted(out)


def generate() -> str:
    lines = [PREAMBLE, "| Element | Python type | Signature | Notes |", "| --- | --- | --- | --- |"]
    lines.extend(f"| {a} | {b} | {c} | {d} |" for a, b, c, d in rows())
    lines.append("")
    lines.append(f"{len(rows())} elements.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the catalogue is stale")
    args = parser.parse_args()

    expected = generate()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != expected:
            print(f"{TARGET.relative_to(ROOT)} is stale — run scripts/generate_tag_catalog.py")
            return 1
        print(f"{TARGET.relative_to(ROOT)} is current")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(rows())} elements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
