name: Python Tests with pytest

on:
  push:
    branches:
      - main  # Substitua 'main' pelo nome da sua branch principal

jobs:
  test:
    name: Test on Python 3.11
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt  # Substitua pelo comando real para instalar as dependências

    - name: Run tests with pytest and coverage
      run: |
        pytest --cov=app --cov-report=xml --cov-report=term

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
